map_server:
  ros__parameters:
    frame_id: map   
    topic_name: map
    use_sim_time: false
    yaml_filename: "/home/endeleze/Desktop/ros2/UNav_ws/src/Collaborate_mapping/Collaborate_mapping/maps/map1.yaml"
